export const destinations = [
  {
    id: "srinagar",
    name: "Srinagar",
    region: "Kashmir",
    tagline: "The Venice of the East",
    description:
      "Srinagar, the summer capital of Jammu and Kashmir, is renowned for its pristine lakes, Mughal gardens, and traditional houseboats. The city offers a perfect blend of natural beauty and rich cultural heritage.",
    image: "Srinagar Dal Lake with houseboats and Zabarwan mountains backdrop",
    bestTime: "April to October",
    altitude: "1,585 meters",
    temperature: "Summer: 15-30°C, Winter: -5-15°C",
    highlights: [
      "Dal Lake and Houseboat Experience",
      "Mughal Gardens (Shalimar, Nishat, Chashme Shahi)",
      "Hazratbal Shrine",
      "Old City and Traditional Markets",
      "Shikara Rides",
      "Floating Gardens",
    ],
    topSights: [
      {
        name: "Dal Lake",
        description: "The jewel of Srinagar, famous for houseboats and shikaras",
        tips: "Best experienced during sunrise and sunset",
      },
      {
        name: "Shalimar Bagh",
        description: "Magnificent Mughal garden built by Emperor Jahangir",
        tips: "Visit during spring for blooming flowers",
      },
      {
        name: "Hazratbal Shrine",
        description: "Revered Muslim shrine housing a relic of Prophet Muhammad",
        tips: "Dress modestly and respect local customs",
      },
      {
        name: "Pari Mahal",
        description: "Seven-terraced garden with panoramic city views",
        tips: "Perfect for photography during golden hour",
      },
    ],
    localTips: [
      "Stay in a traditional houseboat for authentic experience",
      "Try local Kashmiri cuisine like Rogan Josh and Kahwa",
      "Shop for authentic Pashmina shawls and carpets",
      "Respect local customs and dress modestly at religious sites",
      "Bargain politely in local markets",
      "Keep warm clothes even in summer as evenings can be cool",
    ],
    activities: ["Houseboat Stay", "Shikara Rides", "Garden Tours", "Shopping", "Photography", "Cultural Tours"],
    nearbyAttractions: ["Gulmarg (52 km)", "Pahalgam (95 km)", "Sonamarg (80 km)"],
  },
  {
    id: "gulmarg",
    name: "Gulmarg",
    region: "Kashmir",
    tagline: "Meadow of Flowers",
    description:
      "Gulmarg is a picturesque hill station known for its lush green meadows, snow-capped peaks, and world-class skiing facilities. It's home to one of the highest golf courses in the world.",
    image: "Gulmarg meadows with snow peaks and gondola cable car",
    bestTime: "Summer: April-June, Winter: December-March",
    altitude: "2,650 meters",
    temperature: "Summer: 10-25°C, Winter: -10-5°C",
    highlights: [
      "Gondola Cable Car (Phase I & II)",
      "Apharwat Peak",
      "World's Highest Golf Course",
      "Skiing and Snow Activities",
      "Alpine Meadows",
      "Khilanmarg Valley",
    ],
    topSights: [
      {
        name: "Gulmarg Gondola",
        description: "Two-phase cable car system reaching Apharwat Peak",
        tips: "Book tickets early, especially during peak season",
      },
      {
        name: "Apharwat Peak",
        description: "Snow-covered peak accessible via Gondola Phase II",
        tips: "Carry warm clothes and sunglasses even in summer",
      },
      {
        name: "Gulmarg Golf Course",
        description: "One of the highest golf courses in the world",
        tips: "Open only during summer months (May-October)",
      },
      {
        name: "Khilanmarg",
        description: "Beautiful meadow with panoramic mountain views",
        tips: "Accessible by pony ride or short trek",
      },
    ],
    localTips: [
      "Carry altitude sickness medication",
      "Book gondola tickets in advance during peak season",
      "Dress in layers as weather can change quickly",
      "Try local trout fish and Kashmiri tea",
      "Respect the fragile alpine environment",
      "Check weather conditions before planning outdoor activities",
    ],
    activities: ["Gondola Ride", "Skiing", "Golf", "Trekking", "Photography", "Horse Riding"],
    nearbyAttractions: ["Srinagar (52 km)", "Tangmarg (13 km)", "Baramulla (56 km)"],
  },
  {
    id: "pahalgam",
    name: "Pahalgam",
    region: "Kashmir",
    tagline: "Valley of Shepherds",
    description:
      "Pahalgam is a scenic hill station situated at the confluence of streams from Sheshnag Lake and the Lidder River. It serves as the base camp for the annual Amarnath Yatra pilgrimage.",
    image: "Pahalgam valley with Lidder River and pine forests",
    bestTime: "April to October",
    altitude: "2,130 meters",
    temperature: "Summer: 10-25°C, Winter: -5-10°C",
    highlights: [
      "Betaab Valley",
      "Aru Valley",
      "Chandanwari",
      "Baisaran Meadows",
      "Lidder River",
      "Amarnath Yatra Base",
    ],
    topSights: [
      {
        name: "Betaab Valley",
        description: "Picturesque valley named after Bollywood movie 'Betaab'",
        tips: "Perfect for picnics and photography",
      },
      {
        name: "Aru Valley",
        description: "Pristine valley with meadows and trekking trails",
        tips: "Base for treks to Kolahoi Glacier and Tarsar Lake",
      },
      {
        name: "Chandanwari",
        description: "Starting point of Amarnath Yatra pilgrimage",
        tips: "Visit during summer for snow activities",
      },
      {
        name: "Baisaran",
        description: "Mini Switzerland of Kashmir with lush meadows",
        tips: "Accessible by pony ride through pine forests",
      },
    ],
    localTips: [
      "Best time for river rafting is May to September",
      "Carry comfortable trekking shoes",
      "Try fresh trout from Lidder River",
      "Book accommodation in advance during Amarnath season",
      "Respect the pristine environment",
      "Check river conditions before water activities",
    ],
    activities: ["River Rafting", "Trekking", "Fishing", "Horse Riding", "Camping", "Photography"],
    nearbyAttractions: ["Srinagar (95 km)", "Anantnag (45 km)", "Gulmarg (140 km)"],
  },
  {
    id: "sonamarg",
    name: "Sonamarg",
    region: "Kashmir",
    tagline: "Meadow of Gold",
    description:
      "Sonamarg is a pristine hill station known for its golden meadows, glaciers, and alpine lakes. It's the gateway to Ladakh via the Zoji La pass and offers spectacular trekking opportunities.",
    image: "Sonamarg golden meadows with Thajiwas Glacier backdrop",
    bestTime: "May to October",
    altitude: "2,800 meters",
    temperature: "Summer: 5-20°C, Winter: -15-0°C",
    highlights: [
      "Thajiwas Glacier",
      "Zoji La Pass",
      "Krishnasar Lake",
      "Vishansar Lake",
      "Baltal Valley",
      "Alpine Meadows",
    ],
    topSights: [
      {
        name: "Thajiwas Glacier",
        description: "Accessible glacier offering snow activities year-round",
        tips: "Pony rides available, carry warm clothes",
      },
      {
        name: "Zoji La Pass",
        description: "High mountain pass connecting Kashmir to Ladakh",
        tips: "Open only during summer months, check road conditions",
      },
      {
        name: "Krishnasar Lake",
        description: "High-altitude alpine lake surrounded by mountains",
        tips: "Requires trekking, best for experienced hikers",
      },
      {
        name: "Baltal",
        description: "Base camp for Amarnath Yatra via shorter route",
        tips: "Extremely cold even in summer, carry proper gear",
      },
    ],
    localTips: [
      "Road may be closed in winter due to heavy snowfall",
      "Carry altitude sickness medication",
      "Book ponies in advance for glacier visits",
      "Pack warm clothes even in summer",
      "Respect the fragile high-altitude ecosystem",
      "Check weather and road conditions before travel",
    ],
    activities: ["Glacier Trekking", "Photography", "Camping", "Pony Rides", "Alpine Lake Visits"],
    nearbyAttractions: ["Srinagar (80 km)", "Kargil (120 km)", "Baltal (15 km)"],
  },
  {
    id: "leh",
    name: "Leh",
    region: "Ladakh",
    tagline: "Land of High Passes",
    description:
      "Leh, the former capital of the Himalayan kingdom of Ladakh, is a high-altitude desert town known for its Buddhist monasteries, stunning landscapes, and unique culture.",
    image: "Leh city with Buddhist monasteries and barren mountains",
    bestTime: "May to September",
    altitude: "3,500 meters",
    temperature: "Summer: 10-30°C, Winter: -20-5°C",
    highlights: [
      "Leh Palace",
      "Shanti Stupa",
      "Hemis Monastery",
      "Thiksey Monastery",
      "Magnetic Hill",
      "Hall of Fame Museum",
    ],
    topSights: [
      {
        name: "Leh Palace",
        description: "17th-century palace offering panoramic views of Leh",
        tips: "Visit during sunset for best photography",
      },
      {
        name: "Shanti Stupa",
        description: "White-domed Buddhist stupa with 360-degree views",
        tips: "Perfect for sunrise and sunset views",
      },
      {
        name: "Hemis Monastery",
        description: "Largest and wealthiest monastery in Ladakh",
        tips: "Visit during Hemis festival in June/July",
      },
      {
        name: "Thiksey Monastery",
        description: "12-story monastery resembling Potala Palace",
        tips: "Attend morning prayers for authentic experience",
      },
    ],
    localTips: [
      "Acclimatize for 2-3 days before any strenuous activity",
      "Drink plenty of water and avoid alcohol initially",
      "Respect Buddhist customs and traditions",
      "Try local Ladakhi cuisine like Thukpa and Momos",
      "Shop for authentic Pashmina and Tibetan artifacts",
      "Carry sunscreen and sunglasses due to high altitude",
    ],
    activities: ["Monastery Tours", "Cultural Experiences", "Trekking", "River Rafting", "Mountain Biking"],
    nearbyAttractions: ["Nubra Valley (120 km)", "Pangong Lake (160 km)", "Khardung La (40 km)"],
  },
  {
    id: "nubra-valley",
    name: "Nubra Valley",
    region: "Ladakh",
    tagline: "Valley of Flowers",
    description:
      "Nubra Valley is a high-altitude cold desert with sand dunes, double-humped camels, and ancient monasteries. It's accessible via the world's highest motorable pass, Khardung La.",
    image: "Nubra Valley sand dunes with double-humped Bactrian camels",
    bestTime: "May to September",
    altitude: "3,048 meters",
    temperature: "Summer: 15-35°C, Winter: -20-10°C",
    highlights: [
      "Hunder Sand Dunes",
      "Double-humped Camel Safari",
      "Diskit Monastery",
      "Khardung La Pass",
      "Sumur Village",
      "Panamik Hot Springs",
    ],
    topSights: [
      {
        name: "Hunder Sand Dunes",
        description: "Cold desert with unique double-humped camels",
        tips: "Best time for camel safari is early morning or evening",
      },
      {
        name: "Diskit Monastery",
        description: "Oldest monastery in Nubra Valley with giant Buddha statue",
        tips: "Climb to the Buddha statue for panoramic valley views",
      },
      {
        name: "Khardung La Pass",
        description: "World's highest motorable pass at 18,380 feet",
        tips: "Carry oxygen and warm clothes, don't stay long due to altitude",
      },
      {
        name: "Panamik Hot Springs",
        description: "Natural hot springs with therapeutic properties",
        tips: "Carry towels and change of clothes",
      },
    ],
    localTips: [
      "Inner Line Permit required for Indian nationals",
      "Carry sufficient cash as ATMs are limited",
      "Respect local Balti culture and traditions",
      "Try local apricots and sea buckthorn products",
      "Book accommodation in advance as options are limited",
      "Carry warm clothes as nights can be very cold",
    ],
    activities: ["Camel Safari", "Monastery Visits", "Hot Springs", "Photography", "Cultural Tours"],
    nearbyAttractions: ["Leh (120 km)", "Turtuk (90 km)", "Siachen Base Camp (80 km)"],
  },
  {
    id: "pangong-lake",
    name: "Pangong Lake",
    region: "Ladakh",
    tagline: "Lake of Changing Colors",
    description:
      "Pangong Tso is a high-altitude endorheic lake famous for its changing colors and pristine beauty. The lake extends from India to Tibet and is one of the most photographed locations in Ladakh.",
    image: "Pangong Lake crystal blue waters with barren mountains reflection",
    bestTime: "May to September",
    altitude: "4,350 meters",
    temperature: "Summer: 5-25°C, Winter: -30-5°C",
    highlights: [
      "Color-changing Lake Waters",
      "Spectacular Mountain Reflections",
      "Chang La Pass",
      "Spangmik Village",
      "Merak Village",
      "Camping under Stars",
    ],
    topSights: [
      {
        name: "Pangong Lake Shore",
        description: "Pristine lake with ever-changing blue hues",
        tips: "Best colors visible during midday sun",
      },
      {
        name: "Chang La Pass",
        description: "Third highest motorable pass in the world",
        tips: "Stop briefly due to extreme altitude",
      },
      {
        name: "Spangmik",
        description: "Last Indian village near the lake",
        tips: "Good spot for camping and photography",
      },
      {
        name: "Merak Village",
        description: "Traditional Changpa nomad settlement",
        tips: "Experience authentic nomadic culture",
      },
    ],
    localTips: [
      "Inner Line Permit mandatory for all visitors",
      "Lake remains frozen from November to April",
      "Carry warm sleeping bags for camping",
      "No mobile network, inform family before going",
      "Respect the fragile high-altitude ecosystem",
      "Carry sufficient food and water supplies",
    ],
    activities: ["Photography", "Camping", "Stargazing", "Cultural Interaction", "Nature Walks"],
    nearbyAttractions: ["Leh (160 km)", "Tso Moriri (200 km)", "Hanle (180 km)"],
  },
  {
    id: "zanskar",
    name: "Zanskar Valley",
    region: "Ladakh",
    tagline: "The Last Shangri-La",
    description:
      "Zanskar is a remote valley known for its pristine landscapes, ancient monasteries, and unique culture. It offers some of the most challenging and rewarding trekking experiences in the Himalayas.",
    image: "Remote Zanskar valley with dramatic mountain landscapes and monastery",
    bestTime: "June to September",
    altitude: "3,500-4,000 meters",
    temperature: "Summer: 5-20°C, Winter: -30-5°C",
    highlights: [
      "Phuktal Monastery",
      "Karsha Monastery",
      "Chadar Trek",
      "Zanskar River",
      "Padum Town",
      "Ancient Rock Carvings",
    ],
    topSights: [
      {
        name: "Phuktal Monastery",
        description: "Monastery built into a cliff face, accessible only by foot",
        tips: "Requires 2-day trek, carry camping gear",
      },
      {
        name: "Karsha Monastery",
        description: "Largest monastery in Zanskar valley",
        tips: "Attend morning prayers for spiritual experience",
      },
      {
        name: "Chadar Trek",
        description: "Winter trek on frozen Zanskar River",
        tips: "Extremely challenging, requires expert guidance",
      },
      {
        name: "Padum",
        description: "Administrative center and gateway to Zanskar",
        tips: "Base for exploring the valley, limited facilities",
      },
    ],
    localTips: [
      "Extremely remote with limited facilities",
      "Carry all necessary supplies and medications",
      "Respect local Zanskari Buddhist culture",
      "Hire local guides for trekking",
      "Weather can change rapidly, be prepared",
      "Satellite phone recommended for emergencies",
    ],
    activities: ["Trekking", "Monastery Visits", "River Rafting", "Cultural Immersion", "Photography"],
    nearbyAttractions: ["Leh (230 km)", "Kargil (240 km)", "Rangdum (120 km)"],
  },
]

export function getDestinationById(id: string) {
  return destinations.find((dest) => dest.id === id)
}

export function getDestinationsByRegion(region: string) {
  return destinations.filter((dest) => dest.region === region)
}
